# FROM alpine:latest
FROM python:alpine
LABEL version="real-url-api"  atuhor="ixinshang"  description="real-url-api"
RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories && \
    apk add --no-cache gcc g++ py3-pip git python3 python3-dev libffi-dev openssl-dev musl-dev libc-dev linux-headers && \
#    apk add --no-cache gcc g++ python python-dev py-pip mysql-dev linux-headers libffi-dev openssl-dev
    pip install flask-restful loguru -i https://pypi.mirrors.ustc.edu.cn/simple/ && \
    git clone https://github.91chi.fun/https://github.com/ixinshang/real-url-api.git && \
    pip3 install -r /real-url-api/requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/    
WORKDIR /real-url-api
EXPOSE 7000
CMD ["python3", "flask_server.py"]
# ENTRYPOINT ["/home/docker-entrypoint-alpine.sh.x"]